### ISSUE TITLE
Angular Admin UI compilation fails in Vendure 3.5.2 due to missing package exports

### ISSUE THREAD

**Issue by glimz** [vendure-ecommerce/vendure#4079]
**Describe the bug**
After upgrading from Vendure 3.5.1 to 3.5.2, the Angular Admin UI compilation fails with module resolution errors. The `@vendure/admin-ui` package's `exports` field in `package.json` only exports the root path (`.`), but the compiled Admin UI extensions attempt to import from subpaths like `@vendure/admin-ui/core`, `@vendure/admin-ui/login`, etc., which are no longer exported.

Vendure: 3.5.2 (upgraded from 3.5.1)
Node: v22.12.0
npm: 11.5.2
Angular: 19.2.4
Error count: 200+ compilation errors
Root cause: The exports field in node_modules/@vendure/admin-ui/package.json only includes: 
"exports": {
    ".": { ... }
}

**To Reproduce**
## Package Versions
```json
{
  "@vendure/admin-ui": "^3.5.2",
  "@vendure/admin-ui-plugin": "3.5.2",
  "@vendure/ui-devkit": "3.5.2",
  "@vendure/core": "3.5.2",
  "@angular-devkit/build-angular": "^19.2.10",
  "@angular/animations": "^19.2.9",
  "@angular/platform-browser-dynamic": "^19.2.9"
}
```

**Expected behavior**

**Actual behavior**
✘ [ERROR] Could not resolve "@vendure/admin-ui/core"

    src/app.module.ts:4:61:
      4 │ ...nt, AppComponentModule, CoreModule } from '@vendure/admin-ui/core';
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./core" is not exported by package "@vendure/admin-ui":

    ../node_modules/@vendure/admin-ui/package.json:27:15:
      27 │     "exports": {
         ╵                ^

  You can mark the path "@vendure/admin-ui/core" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Comment by michaelbromley** [comment]
This appears to be a publishing issue due to a new method of publishing we introduced with v3.5.2.

For now, the work-around is to use v3.5.1 of the admin ui package, it is almost identical, except 3.5.2 includes one small fix: 

Ensure outOfStockThreshold works when global setting is toggled ([b8d5492](https://github.com/vendure-ecommerce/vendure/commit/b8d5492))

**Comment by Anatoliy-Tishaev** [comment]
Downgrade to the `3.5.1` works! 
Many thanks for the highlighted work-around.

**Comment by michaelbromley** [comment]
For anyone following this issue: the fix in #4131 has been verified working with the latest nightly build (`3.5.3-master-202601290259`). 

All subpath imports like `@vendure/admin-ui/core` now resolve correctly. The fix will be included in the next release.
