### ISSUE TITLE
Vendure Admin UI Compilation Error

### ISSUE THREAD

**Issue by d46** [vendure-ecommerce/vendure#3490]
### Describe the bug

When attempting to compile a custom Vendure Admin UI using `compileUiExtensions`, the build fails with multiple errors indicating missing modules from `@vendure/admin-ui/*`. The Angular compiler reports that it cannot resolve module paths such as `@vendure/admin-ui/core`, `@vendure/admin-ui/login`, etc.

This issue occurs in the `compileUiExtensions()` function and does not involve any custom extensions at this stage.

### To Reproduce

1. Configure and run the Vendure server with the following plugin:

   ```ts
   AdminUiPlugin.init({
       route: 'admin',
       port: 5001,
       adminUiConfig: {},
       app: compileUiExtensions({
           outputPath: path.join(__dirname, './custom-admin-ui'),
           extensions: [],
           devMode: true,
       }),
   }),
   ```

2. Attempt to compile or run the server
3. Compilation fails with TS2307 and TS-991010 errors
4. See error output

### Expected behavior

The Admin UI should compile successfully with no missing module errors when no custom extensions are defined and `devMode` is enabled.

### Errors

Sample errors:

```
✘ [ERROR] TS2307: Cannot find module '@vendure/admin-ui/core' or its corresponding type declarations. [plugin angular-compiler]

✘ [ERROR] TS-991010: Value at position 0 in the NgModule.imports of AppModule is not a reference
  Value could not be determined statically. [plugin angular-compiler]
```

### Environment

- **@vendure/core version**: master
- **Node.js version**: 20.19.0
- **Database**: *

### Additional context

- The issue may be related to missing `node_modules` in the compiled output or incorrect path resolution during Angular's static analysis phase.
- All dependencies are installed via `npm install`
- No extensions have been added yet — this is happening on a clean setup.

**Comment by lucatk** [comment]
After an upgrade from 3.1.2 to 3.3.1 I can attest the same issue.

For me it's producing additional errors related to other angular packages as well as the aforementioned @vendure packages:
```
[server] ✘ [ERROR] TS2307: Cannot find module '@angular/platform-browser-dynamic' or its corresponding type declarations. [plugin angular-compiler]
[server] 
[server]     src/main.ts:2:39:
[server]       2 │ ... platformBrowserDynamic } from '@angular/platform-browser-dynamic';
[server]         ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[server] 
[server] 
[server] ✘ [ERROR] TS2307: Cannot find module '@vendure/admin-ui/core' or its corresponding type declarations. [plugin angular-compiler]
[server] 
[server]     src/main.ts:3:30:
[server]       3 │ import { loadAppConfig } from '@vendure/admin-ui/core';
[server]         ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~
[server] 
[server] 
[server] ✘ [ERROR] Could not resolve "@ng-select/ng-select/themes/default.theme.css"
[server] 
[server]     src/global-styles.scss:10:8:
[server]       10 │ @import "@ng-select/ng-select/themes/default.theme.css";
[server]          ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[server] 
```

<details>
<summary>Dependencies</summary>

```
"dependencies": {
    "@angular/cdk": "^19.2.17",
    "@aws-sdk/client-s3": "^3.777.0",
    "@aws-sdk/lib-storage": "^3.777.0",
    "@types/braintree": "^3.3.14",
    "@vendure/admin-ui": "3.3.1",
    "@vendure/admin-ui-plugin": "3.3.1",
    "@vendure/asset-server-plugin": "3.3.1",
    "@vendure/core": "3.3.1",
    "@vendure/email-plugin": "3.3.1",
    "@vendure/payments-plugin": "^3.3.1",
    "@vendure/ui-devkit": "3.3.1",
    "@wordpress/autop": "^4.23.0",
    "array-move": "^4.0.0",
    "better-sqlite3": "9.6.0",
    "braintree": "^3.30.0",
    "concurrently": "8.2.2",
    "dotenv": "16.4.5",
    "intl-number-parser": "^1.0.5",
    "mongodb": "^5.9.2",
    "openapi-fetch": "^0.14.0",
    "pg": "^8.14.0",
    "puppeteer": "24.4.0",
    "react-currency-input-field": "^3.9.0",
    "react-hook-form": "^7.54.2",
    "rxjs": "^7.8.1",
    "sharp": "^0.34.1",
    "stripe": "^13.11.0"
  },
  "devDependencies": {
    "@flydotio/dockerfile": "^0.7.8",
    "@swc/core": "^1.7.26",
    "@types/react": "19.0.10",
    "@vendure/cli": "3.3.1",
    "@vendure/testing": "^3.3.1",
    "graphql-tag": "^2.12.6",
    "node-fetch": "^2.7.0",
    "nodemon": "^3.1.4",
    "openapi-typescript": "^7.8.0",
    "pdf.js-extract": "^0.2.1",
    "typescript": "5.8.3",
    "unplugin-swc": "^1.5.1",
    "vitest": "^2.1.1"
  },
```
</details>

**Comment by michaelbromley** [comment]
@d46 is this still an issue for you in the latest version?
