### ISSUE TITLE
UI Devkit's scaffolding tsconfig leads to Admin UI compilation failure (es2017 -> es2019)

### ISSUE THREAD

**Issue by mattgills** [vendure-ecommerce/vendure#1859]
**Describe the bug**
As a follow up to #1728, the `ui-devkit` scaffolding still contains a reference to `es2017`.  Therefore, if you are building the Admin UI with extensions (i.e, via `compileUiExtensions`), then the `Array.flat()` will cause a compilation error.

**To Reproduce**
1. Create a dev server and configure the `AdminUiPlugin` to utilize `compileUiExtensions`
2. The compilation will fail with the same error described in #1728 

**Expected behavior**
The `ui-devkit` scaffolding should copy the same `tsconfig` as is stored in the `admin-ui`

**Environment (please complete the following information):**
 - @vendure/core version: 1.8.2
 - Nodejs version: 16.16.0
 - Database (mysql/postgres etc): postgres

**Additional context**
N/A

**Comment by mattgills** [comment]
@michaelbromley I'm going to work on a fix for this between today and tomorrow if you would like to assign to me
